name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build-backend
      run: cd backend && go build

    - name: Test-backend
      run: cd backend && go test

    - name: Build-frontend
      run: cd frontend && go build

    - name: Test-frontend
      run: cd frontend && go test
